# Generated by Django 4.1.2 on 2022-11-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sport',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='location',
            name='longtitude',
            field=models.FloatField(default=0.0),
        ),
    ]
